### ISSUE TITLE
Regarding the MOPline workflow for merging, should I consider merging both cases and controls simultaneously?

### ISSUE THREAD

**Issue by jingydz** [stat-lab/MOPline#15]
Hello, I have a set of structural variations (SVs) from a case cohort and another set from a control cohort, with an imbalanced case-control ratio. I would like to know if I can execute the MOPline workflow separately for these two cohorts, or must I combine the case and control cohorts to run the MOPline workflow together? Since there is a step of re-genotyping, I am concerned that running them separately might produce significant differences. Do you have any suggestions?

**Comment by stat-lab** [comment]
Since SMC genotyping is more efficient as the number of samples with similar genetic backgrounds increases, it is recommended to run 'mopline join_call' with all vcf files of cases and controls to obtain a single joint vcf file. After the joint calling, 'mopline smc' and 'moline filter' steps can be performed with the joint-call vcf file. If necessary, you can split the final vcf file into a case vcf file and a control vcf file.
