### ISSUE TITLE
haploid genomes

### ISSUE THREAD

**Issue by mmpust** [stat-lab/MOPline#8]
Thanks for developing and sharing MOPline!
Are there options to use this with prokaryotes/haploid genomes?
Thanks,
Marie

**Comment by stat-lab** [comment]
There are no options to be used for prokaryotes/haploid genomes. Even for haploid genome, MOPline would genotype most SVs to homozygous genotypes but several to heterozygous SVs. Because such heterozygous SVs are likely to be low quality ones in the haploid genome, these should be validated in the downstream analysis whether these are true or false.

**Comment by mmpust** [comment]
Thank you for the quick response!
