### ISSUE TITLE
No inversions are reported in output

### ISSUE THREAD

**Issue by Saeideh-Ashouri** [stat-lab/MOPline#9]
Hello..
Thank you for developing MOPline

I am trying to run it on a number of samples, the tools I used are MANTA, DELLY, CNVnator, Lumpy, and GRIDSS. I noticed that there are no inversions reported in the output of merged file for each sample. 

Do you have any ideas why it is happening in my data? 
Is there anything I can do for it?

Thank you in advance

**Comment by Saeideh-Ashouri** [comment]
Hello again,

I checked the tool config file and I think I realized the reason behind that.
Here I post a screenshot of the part related to inversions:
<img width="655" alt="Screenshot 2023-12-27 at 13 25 17" src="https://github.com/stat-lab/MOPline/assets/54089274/334ff3ff-7119-4a10-bb4b-b4e070814f0d">

I want to modify the config file so that MOPline can report the inversions in my samples. For this, how would you recommend me modify the file for inversions?

I have another question:
GRIDSS is usually used for detecting insertions too (in addition to Manta). However,  in the config file, GRIDSS is not considered as a program reporting insertions. Are there any specific reason you didn't consider it for calling insertions in MOPline?

Thank you in advance

**Comment by stat-lab** [comment]
In your case, only overlap calls between Manta and DELLY for middle INVs and overlap calls between Manta and GRIDSS for large INVs can be detected with MOPline. The tool combination for overlap calls indicated in SVtool_pairs_config.txt is based on our evaluation results for tools' precision and recall. You can modify the combination of tools in SVtool_pairs_config.txt, but should select better combinations of tools and the minimum number of support reads (the number followed by '${tool_name}:'). Please refer to our previous paper (Kosugi et al., Genome Biol 2019) for selecting good tool pairs. I recommend adding Wham or inGAP-sv to detect INVs.

For INS, only Manat result is used for INS calling in your tool set since our evaluation suggests that GRIDSS INS calls are not useful resource for our preset tool set such as MOPline-7t. I recommend adding inGAP-sv or INSurVeyor to recover INSs.

**Comment by Saeideh-Ashouri** [comment]
Thank you so much for your prompt reply.
Here I close this issue.
